coverage:
  precision: 2
  round: down
  range: "50...100"

  status:
    project:
      default: false
      infinitest-runner:
        target: auto
        base: auto
        threshold: 0.5%
        paths: "infinitest-runner/*"
      infinitest-lib:
        target: auto
        base: auto
        threshold: 0.5%
        paths: "infinitest-lib/*"
      infinitest-eclipse:
        target: auto
        base: auto
        threshold: 0.5%
        paths: "infinitest-eclipse/*"
      infinitest-intellij:
        target: auto
        base: auto
        threshold: 0.5%
        paths: "infinitest-intellij/*"
    patch: off
    changes: off
comment:
  layout: "diff"