coverage:
  precision: 2
  round: down
  range: "50...100"

  status:
    project:
      default:
        target: auto
        if_no_uploads: error
        threshold: 1%
      

    patch:
      default: false
      infinitest-runner:
        target: auto
        paths: "infinitest-runner/*"
      infinitest-lib:
        target: auto
        paths: "infinitest-lib/*"
      infinitest-eclipse:
        target: 40
        paths: "infinitest-eclipse/*"
      infinitest-intellij:
        target: 40
        paths: "infinitest-intellij/*"

    changes: true
