package org.infinitest;

// DEBT Should split this listener
public interface TestQueueListener extends ReloadListener
{
    /**
     * Called when the contents of the test queue changes. When the size of the queue reaches zero,
     * the test run is complete.
     */
    void testQueueUpdated(TestQueueEvent event);

    /**
     * Called when all the work generated by an update is complete. This is called <b>after</b> the
     * last test queue event is fired (where the size of the queue is zero). This will be called
     * even if no tests were actually queued and run.
     */
    void testRunComplete();

}
